export const GET_MOVIE = 'GET_MOVIE';
export const ALPHABET_PRESSED = 'ALPHABET_PRESSED';
export const DELETE_ANSWER_KEY = 'DELETE_ANSWER_KEY';
export const VERIFY_ANSWER_WITH_ACTION = 'VERIFY_ANSWER_WITH_ACTION';
export const REVEAL_ANSWER_KEY = 'REVEAL_ANSWER_KEY';
